keys:
  # Admin devices
  - &admin_nixos_devbox "age1ujmqwrphlu65y57y8cstg3mtcwuxf7640ef3ezd9a6dej5q6jpdqapnvf8"
  - &admin_school_laptop "age1xkt3kv7ycd5dh4lqk38kpf7tqvfaj4xqaz57p80qhan9s99p0cyshj0r5f"
  # - &admin_desktop "AGE-RECIPIENT-FOR-desktop"

  # Other devices
  - &core_vm_gitea_01 "age1ck97naztjgqjapjxdxulnrwpc2h8lkhynw53v4y2y3dm2vdqydls9sp0l0"
  - &core_vm_nixhelper_01 "age1y380h5hld5pafedjjgzcuhnaw06q5ptlt8dy8v25mn08tjkr4uvsgfwmwx"
  #- &laptop "AGE-RECIPIENT-FOR-laptop"

creation_rules:
  # Shared secrets for admins only
  - path_regex: secrets/common\.ya?ml
    key_groups:
      - &admin_group
        age:
          - *admin_nixos_devbox
          - *admin_school_laptop
          # - *admin_desktop

  # Admin device secrets
  - path_regex: secrets/hosts/school-laptop\.ya?ml
    key_groups:
      - *admin_group

  - path_regex: secrets/hosts/nixos-devbox\.ya?ml
    key_groups:
      - *admin_group

  - path_regex: secrets/hosts/desktop\.ya?ml
    key_groups:
      - *admin_group

  # Non-admin device secrets: admin + device keys in same group (either can decrypt)
  - path_regex: secrets/hosts/laptop\.ya?ml
    key_groups:
      - age:
          - *admin_nixos_devbox
          - *admin_school_laptop
          #- *laptop

  - path_regex: secrets/hosts/core-vm-gitea-01\.ya?ml
    key_groups:
      - age:
          - *admin_nixos_devbox
          - *admin_school_laptop
          - *core_vm_gitea_01

  - path_regex: secrets/hosts/core-vm-nixhelper-01\.ya?ml
    key_groups:
      - age:
          - *admin_nixos_devbox
          - *admin_school_laptop
          - *core_vm_nixhelper_01

  # Service secrets
  - path_regex: secrets/service/mail\.ya?ml
    key_groups:
      - age:
          - *admin_nixos_devbox
          - *admin_school_laptop
          - *core_vm_gitea_01
  - path_regex: secrets/service/builder\.ya?ml
    key_groups:
      - age:
          - *admin_nixos_devbox
          - *admin_school_laptop
          - *core_vm_gitea_01
          - *core_vm_nixhelper_01
 
